/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Michi' at '01.11.15 14:57' with Gradle 2.6
 *
 * @author Michi, @date 01.11.15 14:57
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
